<MyGridLayout>
    GridLayout:
        cols : 1
        size : root.width, root.height

        Image: 
            source :'Hudson_sollutions_white.png'
            pos_hint : {'center_x' : 1, 'center_y' : 1 }
        Label:
            text : 'Select country'
        TextInput: 
            multiline : False
        Label:
            text : 'Select city'
        TextInput: 
            multiline : False
        Button:
            text : "OK"